name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Lint
      run: ./gradlew lint

    - name: Run Tests
      run: ./gradlew test

    - name: Upload Lint Report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html
